controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  legged_controller:
    type: legged/LeggedController
  legged_controller_from_topic_estimate:
    type: legged/LeggedControllerFromTopicEstimate
  legged_cheater_controller:
    type: legged/LeggedCheaterController
  stand_up_controller:
    type: legged/StandUpController
  lie_down_controller:
    type: legged/LieDownController
